export const auditEventCategories = [
  "authentication",
  "navigation",
  "form_submission",
  "data_change",
  "administration",
] as const;

export type AuditEventCategory = (typeof auditEventCategories)[number];

export const auditEventActions = [
  "auth.login",
  "auth.logout",
  "view.screen",
  "form.submit",
  "data.update",
  "data.delete",
  "data.clear",
  "data.import_preview",
  "data.import",
  "production_plan.save",
  "production_brand.create",
  "production_brand.correct",
  "production_brand.delete",
  "production_brand.merge",
  "production_brand.import",
  "raw_material_nomenclature.create",
  "raw_material_nomenclature.correct",
  "refractory_report.submit",
  "refractory_report.approve",
  "refractory_report.reject",
  "refractory_wagon.create",
  "refractory_wagon.correct",
  "refractory_wagon.inspect",
  "laboratory_result.submit",
  "laboratory_bank.assign",
  "rotary_kiln_2_firing_record.submit",
  "rotary_kiln_2_firing_record.correct",
  "laboratory_sample_registration.submit",
  "laboratory_sample_registration.correct",
  "laboratory_unshaped_product_sample.submit",
  "laboratory_unshaped_product_sample.correct",
  "laboratory_formed_product_sample.submit",
  "laboratory_formed_product_sample.correct",
  "laboratory_verification.submit",
  "laboratory_verification.correct",
  "laboratory_raw_material_quality.submit",
  "laboratory_raw_material_quality.correct",
  "laboratory_raw_material_warehouse.submit",
  "laboratory_raw_material_warehouse.approve",
  "laboratory_raw_material_warehouse.correct",
  "laboratory_green_product_quality.submit",
  "laboratory_green_product_quality.correct",
  "laboratory_chemical_analysis.submit",
  "laboratory_chemical_analysis.correct",
  "board_assignment.create",
  "board_assignment.update",
  "board_assignment.document_upload",
  "board_assignment.document_delete",
  "board_assignment.submit_for_review",
  "board_assignment.return_for_revision",
  "board_assignment.complete",
  "admin.account_create",
  "admin.account_archive",
  "admin.account_login_enable",
  "admin.account_login_disable",
  "admin.account_protection_enable",
  "admin.account_protection_disable",
  "admin.account_password_reset",
  "admin.account_position_update",
  "admin.account_notification_contacts_update",
  "admin.account_notification_channels_update",
  "admin.position_notification_permission_update",
  "account.notification_settings_update",
  "admin.position_create",
  "admin.position_update",
  "admin.position_protection_enable",
  "admin.position_protection_disable",
  "admin.position_admin_rights_enable",
  "admin.position_admin_rights_disable",
  "admin.position_order_update",
  "admin.position_navigation_access_update",
  "admin.navigation_order_update",
  "admin.position_delete",
] as const;

export type AuditEventAction = (typeof auditEventActions)[number];

export const auditTargetTypes = [
  "auth_session",
  "screen",
  "dispatcher_submission",
  "equipment_report",
  "database_section",
  "database_row",
  "dispatcher_import",
  "user_account",
  "account_position",
  "production_plan",
  "production_brand",
  "raw_material_nomenclature",
  "refractory_report",
  "refractory_wagon",
  "laboratory_result",
  "laboratory_bank_assignment",
  "rotary_kiln_2_firing_record",
  "laboratory_sample_registration",
  "laboratory_unshaped_product_sample",
  "laboratory_formed_product_sample",
  "laboratory_verification",
  "laboratory_raw_material_quality",
  "laboratory_raw_material_warehouse_movement",
  "laboratory_green_product_quality",
  "laboratory_chemical_analysis",
  "board_assignment",
  "navigation_order",
] as const;

export type AuditTargetType = (typeof auditTargetTypes)[number];

export type AuditEventOutcome = "success" | "failure";
